POST http://localhost:3000/recipe/agsdafsdvec
content-type: application/json

{


  "title": "adfhgad",

  "description": "Sahgasdf",

  "time_minutes": 123,

  "price": 134

}


### Get an estimate for an existing vehicle -> url is string and received as string

Get http://localhost:3000/recipe/agsdafsdvec


### Add Ingredient to the recipe

POST http://localhost:3000/recipe/1/ingredient
{
  "name": "aspharagus",
}
### Remove Ingredient to the recipe

POST http://localhost:3000/recipe/1/ingredient
{
  "name": "aspharagus",
}
### GET Ingredient to the recipe

GET http://localhost:3000/recipe/1
