name: Recipe CI
on:
  push:
    branches: [main, prod]
  pull_request:
    branches: [main, prod]
jobs:
  build:
    env:
      CI: true
      PORT: 3000

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
