name: Recipe CI
on:
  push:
    branches: [main, prod]
  pull_request:
    branches: [main, prod]
jobs:
  build:
    env:
      CI: true
      PORT: 3000

    steps:
      - uses: actions/checkout@v2
