name: Recipe CI
on:
  push:
    branches: ['main', 'prod']
  pull_request:
    branches: ['main', 'prod']
jobs:
  build:
    env:
      CI: true
      PORT: 3000
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
